version: '3.8'
services:
  #app:
    #build: .
    #ports:
    #  - 8000:8000
    #volumes:
    #  - ./Users/GilbertYan/CodeDancer/My_Temp/python:/code
    #command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload
    #restart: "no"
    #pull_policy: if_not_present
    #depends_on:
    #  - ollama
    #  - ollama-webui
    #networks:
    #  - ollama-docker-compose

  ollama:
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    volumes: 
      - type: bind
        source: ./mnt/ollama
        target: /root/.ollama
        read_only: false
    container_name: ollama
    pull_policy: if_not_present
    tty: true
    restart: "no"
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - ollama-docker-compose

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    pull_policy: if_not_present
    volumes:
      - ./mnt/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 3000:8080
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=http://host.docker.internal:11434
      - ENV=prod
      - WEBUI_AUTH=False
      - WEBUI_NAME=GeekBBer
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - ollama-docker-compose
    restart: "no"

networks:
  ollama-docker-compose:
    external: false
